### ISSUE TITLE
Challenge Information are not saveable

### ISSUE THREAD

**Issue by TA2k** [iobroker-community-adapters/ioBroker.acme#37]
When you enter challenge information it not possible to save them
and
Because of number type for port its hard to remove the content of the input and enter for example 80

<img width="902" alt="image" src="https://github.com/iobroker-community-adapters/ioBroker.acme/assets/1307684/b2747b4d-c007-4216-ad20-ca2dbbaf3f22">

error in log
``
TypeError: this.getCertificateCollectionAsync is not a function at Acme.onReady (/opt/iobroker/node_modules/iobroker.acme/main.js:71:40) at Acme.emit (node:events:514:28) at Acme._callReadyHandler (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:9028:18) at /opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:9006:26
``

**Comment by TA2k** [comment]
solved with 0.1.0
